# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
  ];
  boot.initrd.kernelModules = [
    "dm-snapshot" # For LUKS
    "mei" # Load mei module to fix drm error
    "mei_me"
    "mei_gsc_proxy"
    "mei_hdcp"
    "mei_pxp"
  ];
  boot.initrd.luks.devices."crypted" = {
    # Device for "crypted" is set in disko.nix
    crypttabExtraOpts = [ "password-echo=no" ];
  };
  # This one is cool: https://github.com/aaron-p1/nixconfig/blob/85cca6f72e41bceaef0415b3017212597026ea41/hosts/aaron-laptop/hardware-configuration.nix#L29

  boot.kernelParams = [
    "initcall_blacklist=sysfb_init" # Workaround for empty lines after Setting Up Virtual Console
    "video=eDP-1:2880x1800@60"
    "video=DP-1:2560x1440@60" # 4K@60 is denied by i915 driver
    "video=HDMI-A-1:2560x1440@60"
  ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u2u4.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
